"use strict";
var mongo = require("./mongoFunctions");
var q = require('q');
var raids = function() {

    return {
        highmaul: {

            "0kargath"
                :
            {
                "embeddedUrl"
                    :
                    "D5QqzwJIPa0",
                "name"
                    :
                    "Kargath Bladefist",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/kargath-bladefist-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "KpzfmKTZp8U",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/kargath.png",
                "wowheadNPCNum"
                    :
                    "87444"
            }
            ,
            "1butcher"
                :
            {
                "embeddedUrl"
                    :
                    "QkLExQUJgW4",
                "name"
                    :
                    "The Butcher",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/the-butcher-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "yIS0jjmcFgE",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/theButcher.png",
                "wowheadNPCNum"
                    :
                    "87447"
            }
            ,
            "2Tectus"
                :
            {
                "embeddedUrl"
                    :
                    "C0VYzWNYDF0",
                "name"
                    :
                    "Tectus",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/tectus-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "wNbJmeNLkjo",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/tectus.png",
                "wowheadNPCNum"
                    :
                    "87446"
            }
            ,
            "3brackenspore"
                :
            {
                "embeddedUrl"
                    :
                    "mIdrE_7iqc8",
                "name"
                    :
                    "Brackenspore",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/brackenspore-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "fsXhQtEKzms",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/brackenspore.png",
                "wowheadNPCNum"
                    :
                    "87441"
            }
            ,
            "4twinOgron"
                :
            {
                "embeddedUrl"
                    :
                    "AJ4xo4jqJlU",
                "name"
                    :
                    "Twin Ogron",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/twin-ogron-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/twinOgron.png",
                "wowheadNPCNum"
                    :
                    "87449"
            }
            ,
            "5koragh"
                :
            {
                "embeddedUrl"
                    :
                    "y9ha5_IkI7A",
                "name"
                    :
                    "Ko'ragh",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/ko-ragh-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "XSeMw7-byOA",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/ko'ragh.png",
                "wowheadNPCNum"
                    :
                    "87445"
            }
            ,
            "6margok"
                :
            {
                "embeddedUrl"
                    :
                    "i4OMq9fYgVY",
                "name"
                    :
                    "Imperator Mar'gok",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/imperator-mar-gok-strategy-guide-preview",
                "embeddedUrlFatboss"
                    :
                    "",
                "embeddedUrlLOSgaming"
                    :
                    "",
                "img"
                    :
                    "Highmaul/imperatorMar'gok.png",
                "wowheadNPCNum"
                    :
                    "87818"
            }
        },
        brf:  {
            "00":
            {
                "embeddedUrl"
                    :
                    "7w6Cxv3C8lc",
                "name"
                    :
                    "Gruul",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/gruul-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "QrN5W7VxZ7Y",
                "embeddedUrlLOSgaming"
                    :
                    "ERVxge6_tPU",
                "wowheadNPCNum"
                    :
                    "76877"
            }
            ,
            "01"
                :
            {
                "embeddedUrl"
                    :
                    "zoZR_twO7VI",
                "name"
                    :
                    "Oregorger",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/oregorger-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "i0mGJkRLz3A",
                "embeddedUrlLOSgaming"
                    :
                    "DDGEPPf6qAE",
                "wowheadNPCNum"
                    :
                    "77182"
            }
            ,
            "02"
                :
            {
                "embeddedUrl"
                    :
                    "FUafR44FBKQ",
                "name"
                    :
                    "The Blast Furnace",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/the-blast-furnace-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "tDzhPwDzdOc",
                "embeddedUrlLOSgaming"
                    :
                    "l772ywX8t0I",
                "wowheadNPCNum"
                    :
                    "76806"
            }
            ,
            "03"
                :
            {
                "embeddedUrl"
                    :
                    "H3JYPNYdCWA",
                "name"
                    :
                    "Hans'gar and Franzok",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/hans-gar-and-franzok-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "FW4zMMtiXsw",
                "embeddedUrlLOSgaming"
                    :
                    "fVMx0PUJTpk",
                "wowheadNPCNum"
                    :
                    "76973"
            }
            ,
            "04"
                :
            {
                "embeddedUrl"
                    :
                    "uRYBm66s3-A",
                "name"
                    :
                    "Flamebender Ka'graz",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/flamebender-ka-graz-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "vAViKBYoAFg",
                "embeddedUrlLOSgaming"
                    :
                    "qikIJxh9wL8",
                "wowheadNPCNum"
                    :
                    "76814"
            }
            ,
            "05"
                :
            {
                "embeddedUrl"
                    :
                    "G4SPS2rV3So",
                "name"
                    :
                    "Kromog",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/kromog-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "0BjCnIuTNbA",
                "embeddedUrlLOSgaming"
                    :
                    "FA0nwh-8CRI",
                "wowheadNPCNum"
                    :
                    "77692"
            }
            ,
            "06"
                :
            {
                "embeddedUrl"
                    :
                    "s9-YdfBoddk",
                "name"
                    :
                    "Beastlord Darmac",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/beastlord-darmac-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "6ThCMYtspNU",
                "embeddedUrlLOSgaming"
                    :
                    "WZzQdwFjvSg",
                "wowheadNPCNum"
                    :
                    "76865"
            }
            ,
            "07"
                :
            {
                "embeddedUrl"
                    :
                    "xxxx",
                "name"
                    :
                    "Operator Thogar",
                "stratUrl"
                    :
                    "http://www.icy-veins.com/wow/operator-thogar-strategy-guide-normal-heroic",
                "embeddedUrlFatboss"
                    :
                    "Yb1KCCMXPeU",
                "embeddedUrlLOSgaming"
                    :
                    "Ccy90cVZiWk",
                "wowheadNPCNum"
                    :
                    "76906"
            }
            ,
            "08"
                :
            {
                "embeddedUrl"
                    :
                    "xxxx",
                "name"
                    :
                    "The Iron Maidens",
                "stratUrl"
                    :
                    "",
                "embeddedUrlFatboss"
                    :
                    "QnXH9Py-8_Y",
                "embeddedUrlLOSgaming"
                    :
                    "2Z_B8xhUEe0",
                "wowheadNPCNum"
                    :
                    "77557"
            }
            ,
            "09"
                :
            {
                "embeddedUrl"
                    :
                    "xxxx",
                "name"
                    :
                    "Blackhand",
                "stratUrl"
                    :
                    "",
                "embeddedUrlFatboss"
                    :
                    "",
                "embeddedUrlLOSgaming"
                    :
                    "pYyjQQxhP44",
                "wowheadNPCNum"
                    :
                    "77325"
            }
        }
    };
};

var getRaidBossInfo = function() {

    var raidInfo ={};
        mongo.getRaidBossInfo().then(function(data){
        raidInfo = data;
        return raidInfo;
    });


};

module.exports = {
    raids:getRaidBossInfo
};